### ISSUE TITLE
not working in nuxt 3.6.5

### ISSUE THREAD

**Issue by Arch4AI** [wobsoriano/nuxt-proxy#28]

**Comment by davidparker333** [comment]
Same issue here. Everything works when running the dev server, but then `yarn build && yarn preview` yields `Cannot find module '<dir>/.output/server/node_modules/unenv/runtime/fetch/index.mjs' imported from <dir>/.output/server/index.mjs`

Edit: It looks like just installing `unenv` as a dependency resolves the issue as a workaround
